### ISSUE TITLE
DragNUWA weight link on GoogleDrive is dead

### ISSUE THREAD

**Issue by AugmentedRealityCat** [chaojie/ComfyUI-DragNUWA#1]
Looks like too many people downloaded the weights as we cannot download them anymore. Here is the message we get:
```

Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

```

**Comment by chaojie** [comment]
you can try this: https://www.liblib.art/modelinfo/e72699771a7b443499ffdd298f58f0a7

**Comment by AugmentedRealityCat** [comment]
It's impossible to download from that link without subscribing.

Can you provide a freely accessible download link, please ?

**Comment by kingzcheung** [comment]
> It's impossible to download from that link without subscribing.
> 
> Can you provide a freely accessible download link, please ?

https://huggingface.co/LanHarmony/DragNUWA
https://huggingface.co/zeqixiao/dragnuwa/tree/main
https://huggingface.co/benjamin-paine/dragnuwa-pruned-safetensors

**Comment by AugmentedRealityCat** [comment]
Thanks a lot for the new links - particularly the last one with the pruned version !
