### ISSUE TITLE
Add to comfyui manager

### ISSUE THREAD

**Issue by mrkennypowers** [chaojie/ComfyUI-DragNUWA#2]
Would it be possible to add this to comfy ui manager?

**Comment by chaojie** [comment]
![image](https://github.com/chaojie/ComfyUI-DragNUWA/assets/701810/a91016ed-8a7f-4557-a3df-33c52179b987)

The project is now on ComfyUI Manager.

**Comment by mrkennypowers** [comment]
Thank you!
