### ISSUE TITLE
When loading the graph, the following node types were not found: Load CheckPoint DragNUWA DragNUWA Run

### ISSUE THREAD

**Issue by guahunyo** [chaojie/ComfyUI-DragNUWA#7]
![image](https://github.com/chaojie/ComfyUI-DragNUWA/assets/18573180/ad2c12cb-98bf-47ae-94a9-0e1f346f816b)
![image](https://github.com/chaojie/ComfyUI-DragNUWA/assets/18573180/a4171f9e-ef5f-4f93-86bd-955283c41262)

**Comment by chaojie** [comment]
pip install -r requirements.txt

**Comment by guahunyo** [comment]
> pip install -r requirements.txt, you can git pull first

我的问题解决了 我的模型之前是放在sdwebui的文件夹里 comfyui这边改了模型的引用地址  有些工作流不能这么玩 还是得把模型扔到comfyui的model文件夹里才能跑
