### ISSUE TITLE
依赖在不同环境下有比较大的问题

### ISSUE THREAD

**Issue by kingzcheung** [chaojie/ComfyUI-DragNUWA#9]
比如 `tokenizers==0.12.1`，在 rust 编译器 1.7x 环境下会出现以下错误:
```
casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell`
```
原因在这里： https://github.com/huggingface/tokenizers/issues/1402

比如 torch>=2.0.1 ，但是在一些依赖中强制指定了 `torch!=2.0.1,>=1.13.1`
同时 torchaudio也会出现 `libtorchaudio.so: undefined symbol: _ZN3c104cuda9SetDeviceEi` 错误。

以上都会造成这个问题： https://github.com/chaojie/ComfyUI-DragNUWA/issues/7

这是我在我的conda 环境中修正后运行正确的的依赖版本：

```
black==23.7.0
chardet==5.1.0
clip @ git+https://github.com/openai/CLIP.git
einops>=0.6.1
fairscale>=0.4.13
fire>=0.5.0
fsspec>=2023.6.0
invisible-watermark>=0.2.0
kornia==0.6.9
matplotlib>=3.7.2
natsort>=8.4.0
ninja>=1.11.1
numpy>=1.24.4
omegaconf>=2.3.0
open-clip-torch>=2.20.0
opencv-python==4.6.0.66
pandas>=2.0.3
pillow>=9.5.0
pudb>=2022.1.3
pytorch-lightning==2.0.1
pyyaml>=6.0.1
scipy>=1.10.1
streamlit>=0.73.1
tensorboardx==2.6
timm>=0.9.2
tokenizers==0.15.0
torch>=2.0.2
torchaudio>=2.0.2
torchdata>=0.6.1
torchmetrics>=1.0.1
torchvision>=0.15.2
tqdm>=4.65.0
transformers>=4.19.1
urllib3<1.27,>=1.25.4
wandb>=0.15.6
webdataset>=0.2.33
wheel>=0.41.0
xformers>=0.0.20
colorlog 
deepdish  
json_lines 
msgpack 
configobj 
psutil 
h5py 
imageio 
tensorboard 
moviepy 
pyyaml 
pandas 
einops
```

**Comment by mikeyimer** [comment]
Are these dependencies installed used comfyui/python_embeded/python -m pip install? Will it replace the comfy library and cause a clash?

**Comment by kingzcheung** [comment]
> Are these dependencies installed used comfyui/python_embeded/python -m pip install? Will it replace the comfy library and cause a clash?

I use `conda` to manage my project dependencies, but in fact, there may be dependency conflicts with other plugins, which I need to resolve myself

**Comment by forlandsking** [comment]
太感谢了，整了一晚没解决，现在解决了

**Comment by Inmanguo** [comment]
![4d2e84dc6f1585ed446d254129ca391a7db1186e446e5736fe4af22def3fb0a5QzpcVXNlcnNcVXNlclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMzIwNTQ5MDM0NV92MlxJbWFnZUZpbGVzXDE3MDU1NDY0MTI2MjVfMjZBQzU4NTktOUM3My00ZGYxLTg0ODgtNDBBOTVGNzhCMjBFLnBuZw==](https://github.com/chaojie/ComfyUI-DragNUWA/assets/26617969/b73bba09-e762-4b40-a4d2-648c4a3df659)



can anyone help with this?

**Comment by ffdown** [comment]
> ![4d2e84dc6f1585ed446d254129ca391a7db1186e446e5736fe4af22def3fb0a5QzpcVXNlcnNcVXNlclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMzIwNTQ5MDM0NV92MlxJbWFnZUZpbGVzXDE3MDU1NDY0MTI2MjVfMjZBQzU4NTktOUM3My00ZGYxLTg0ODgtNDBBOTVGNzhCMjBFLnBuZw==](https://private-user-images.githubusercontent.com/26617969/297597453-b73bba09-e762-4b40-a4d2-648c4a3df659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njc5NTksIm5iZiI6MTcwNTU2NzY1OSwicGF0aCI6Ii8yNjYxNzk2OS8yOTc1OTc0NTMtYjczYmJhMDktZTc2Mi00YjQwLWE0ZDItNjQ4YzRhM2RmNjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NzQ1YTMwZjAxMTBmODdiNjA3YzhkODIxYzdiMWI4MmQ5NDNjMGIyN2UwNDAyNGVlZjJkN2U0YWE2Nzg2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-I0Osm_KwVuW7M-w77or6AEnbXYTvIsowxv1YfZDNTs)
> 
> can anyone help with this?

reinstall CUDA pytorch.org
